sensor:

# Outdoor Temperature
  - platform: homeassistant
    id: outdoor_temperature_sensor
    entity_id: sensor.outdoor_temperature

# Office Temperature
  - platform: homeassistant
    id: office_temperature_sensor
    entity_id: sensor.office_temperature

# Office Blinds
  - platform: homeassistant
    id: office_blind_position
    entity_id: cover.office_blind
    attribute: target_lift_position



binary_sensor:

# Devices

  # Office Feature Lights
  - platform: homeassistant
    id: office_feature_lights
    entity_id: light.office_feature_lights

  # Office Storage Lights
  - platform: homeassistant
    id: office_storage
    entity_id: light.office_storage

  # 3d Printer
  - platform: homeassistant
    id: printer_power
    entity_id: switch.office_3d_printer_power

  # 3d Printer Lights
  - platform: homeassistant
    id: printer_lights
    entity_id: switch.office_3d_printer_lights
    
  # Office Air Conditioner
  - platform: homeassistant
    id: office_air_condition
    entity_id: binary_sensor.office_air_conditioner
  
  # Office Blind
  - platform: homeassistant
    id: office_blind
    entity_id: binary_sensor.office_blind_state

  # Office Presence
  - platform: homeassistant
    id: office_presence
    entity_id: binary_sensor.office_presence_presence

  # Lenovo Power
  - platform: homeassistant
    id: office_lenovo_power_state
    entity_id: switch.office_lenovo_power_switch


# Scenes

  # Office Scene Features
  - platform: homeassistant
    id: office_scene_features
    entity_id: binary_sensor.office_scene_features

  # Office Scene Desk Calls
  - platform: homeassistant
    id: office_scene_desk_call
    entity_id: binary_sensor.office_scene_desk_call

  # Office Scene Desk Calls
  - platform: homeassistant
    id: office_scene_evening
    entity_id: binary_sensor.office_scene_evening